---
title: "AHP File"
output: html_document
---
```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
packages = c('ahp', 'readr')
for (p in packages){ 
  if(!require(p, character.only = T)){
    install.packages(p) 
  }
  library(p,character.only = T) 
}
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
houses <- read_csv('data/resale-flat-prices/finalCSVforplots.csv')
```

```{r}
features <- c('busStop', 'clinics','hawkers','mrt','schools','spf')
weight_b_c <- 9  #Weight busstop_clinic. Bus stop is much higher priority than clinic
weight_b_h <- 7
weight_b_m <- 5
weight_b_sc <- 3
weight_b_sp <- 1
weight_c_h <- 1/3
weight_c_m <- 1/4
weight_c_sc <- 1/7
weight_c_sp <- 1/9
weight_h_m <- 1/3
weight_h_sc <- 1/5
weight_h_sp <- 1/6
weight_m_sc <- 1/7
weight_m_sp <- 1/9
weight_sc_sp <- 1/3

#Create preference matrix
prefMatrix <- data.frame(c(1,weight_b_c,weight_b_h,weight_b_m,weight_b_sc,weight_b_sp),
                        c(weight_b_c,1,weight_c_h,weight_c_m,weight_c_sc,weight_c_sp),
                        c(weight_b_h,weight_c_h,1,weight_h_m,weight_h_sc,weight_h_sp),
                        c(weight_b_m,weight_c_m,weight_h_m,1,weight_m_sc,weight_m_sp),
                        c(weight_b_sc,weight_c_sc,weight_h_sc,weight_m_sc,1,weight_sc_sp),
                        c(weight_b_sp,weight_c_sp,weight_h_sp,weight_m_sp,weight_sc_sp,1))

colnames(prefMatrix) <- c(1:6)

prefComb <- data.frame(c(1,2),c(2,3),c(1,2))
#Create AHP Matrix
ahpMat <- AhpMatrix(prefMatrix)

#Calculate the ahp priority weights from the AHP matrix.
priorities <- PrioritiesFromPairwiseMatrixEigenvalues(ahpMat)
priorities$priority
priorityList <- priorities$priority
consistency <- priorities$consistency

print(priorityList)
print("Consistency: ")
print(consistency)
```

```{r}
houses$ahp_test <- houses$min_dist_busStop*priorityList[1] + houses$min_dist_clinic*priorityList[2] +
  houses$min_dist_hawker*priorityList[3] + houses$min_dist_mrt*priorityList[4] +
  houses$min_dist_school*priorityList[5] + houses$min_dist_spf*priorityList[6]
```