---
title: "Project - Plot - Filter"
author: "Shubham Periwal"
date: "April 3, 2019"
---

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
packages = c('sf', 'tmap', 'ggmap', 'rgdal', 'tidyverse', 'qdapTools', 'spatstat', 'readr', 'tmaptools','spatial.tools','raster')
for (p in packages){ 
  if(!require(p, character.only = T)){
    install.packages(p) 
  }
  library(p,character.only = T) 
}
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
houses <- read_csv('data/resale-flat-prices/finalCSVforplots.csv')
houses_sf <- st_as_sf(houses, coords = c("lon", "lat"))
houses_sf <- st_set_crs(houses_sf, 4326)
houses_sf <- st_transform(houses_sf, 3414)

mpsz <- readOGR(dsn='data/mpsz', layer='MP14_SUBZONE_WEB_PL')
mpsz_sf <- st_as_sf(mpsz)
```

#Cut the region

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
tmap_mode('view')

regionArea <- mpsz[mpsz$REGION_N=="NORTH REGION", ]
#bb1 <- bbox(regionArea)

#tahoe_highrez <- brick(system.file("external/tahoe_highrez.tif", package="spatial.tools"))
bbox_to_SpatialPolygons(regionArea)
regionArea_extent <- extent(regionArea)
bbox_to_SpatialPolygons(regionArea_extent,
	CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=SVY21 +towgs84=0,0,0"))
regionAreaz_bbox <- bbox(regionArea)
bbox_to_SpatialPolygons(regionArea_bbox,
	CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=SVY21 +towgs84=0,0,0"))
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

bbox <- get_bbox (c (12386.29, 35330.11, 32377.19, 50256.33))
dat_B <- extract_osm_objects (key = 'building', bbox = bbox)
```



#If user selects REGION ONLY

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
tmap_mode('view')
tm_shape(mpsz[mpsz$REGION_N=="NORTH REGION", ]) + tm_polygons() + 
  tm_shape(houses_sf[houses_sf$REGION_N=="NORTH REGION", ]) +
    tm_dots(col='min_dist_clinic',
            style='quantile',
            size=0.1)
```


#Cut the region

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
tmap_mode('view')

regionArea <- mpsz[mpsz$REGION_N=="NORTH REGION", ]
bbox_new <- st_bbox(regionArea) # current bounding box

xrange <- bbox_new$xmax - bbox_new$xmin # range of x values
yrange <- bbox_new$ymax - bbox_new$ymin # range of y values

# bbox_new[1] <- bbox_new[1] - (0.5 * xrange) # xmin - left
# bbox_new[3] <- bbox_new[3] + (0.5 * xrange) # xmax - right
# bbox_new[2] <- bbox_new[2] - (0.5 * yrange) # ymin - bottom
#  bbox_new[4] <- bbox_new[4] + (0.5 * yrange) # ymax - top

bbox_new <- bbox_new %>%  # take the bounding box ...
  st_as_sfc() # ... and make it a sf polygon

# draw a prettier chart
#mapName <- tm_shape(regionArea, bbox = bbox_new) + tm_polygons() 

tm_shape(mpsz[mpsz$REGION_N=="NORTH REGION",], bbox = bbox_new ) + tm_polygons() + 
  tm_shape(houses_sf[houses_sf$REGION_N=="NORTH REGION", ]) +
    tm_dots(col='min_dist_clinic',
            style='quantile',
            size=0.1)



mapName
```



#Cut the region

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
tmap_mode('view')

regionArea <- mpsz[mpsz$REGION_N=="NORTH REGION", ]
st_bbox(regionArea)
st_bbox(houses_sf)

bb2 <- bb(st_bbox(regionArea))

plot(houses_sf[houses_sf$REGION_N=="NORTH REGION", ])

mapName <- tm_shape(regionArea,
         bbox = st_bbox(regionArea)) + 
  tm_view(set.bounds = st_bbox(regionArea)) +
  tm_polygons()
st_bbox(regionArea)
leaflet::fitBounds(mapName, 12386, 35330, 32377, 50256)
```

link
```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
tmap_mode('view')

regionArea <- mpsz[mpsz$REGION_N=="NORTH REGION", ]
regionBbox <- st_bbox(regionArea, crs= st_crs(mpsz)) %>% st_as_sfc() 
st_bbox(houses_sf)

tm_shape(regionArea,
         bbox = regionBbox) +
  tm_polygons()
st_bbox(regionArea)
leaflet::fitBounds(mapName, 12386, 35330, 32377, 50256)
```



#HISTOGRAM of REGIONS

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
houses_agg <- houses_sf %>% group_by(REGION_N) %>% summarise(mean_dist=mean(min_dist_clinic))

ggplot(houses_agg, aes(x = reorder(REGION_N, -mean_dist),y = mean_dist)) + 
  geom_col() + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```


#HISTOGRAM of 1 region by subzone

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
houses_agg <- houses_sf[houses_sf$REGION_N=="CENTRAL REGION", ] %>% group_by(SUBZONE_N) %>% summarise(mean_dist=mean(min_dist_clinic))

ggplot(houses_agg, aes(x = reorder(SUBZONE_N, -mean_dist),y = mean_dist)) + 
  geom_col() + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

#HISTOGRAM of 1 region by town

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
houses_agg <- houses_sf[houses_sf$REGION_N=="CENTRAL REGION", ] %>% group_by(town) %>% summarise(mean_dist=mean(min_dist_clinic))

ggplot(houses_agg, aes(x = reorder(town, -mean_dist),y = mean_dist)) + 
  geom_col() + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```
#Map Select Subzone

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
tmap_mode('view')
tm_shape(mpsz[mpsz$SUBZONE_N=="SEMBAWANG CENTRAL", ]) + tm_polygons() + 
  tm_shape(houses_sf[houses_sf$SUBZONE_N=="SEMBAWANG CENTRAL", ]) +
    tm_dots(col='min_dist_clinic',
            style='quantile',
            size=0.1)
```

#Map Select Town

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
tmap_mode('view')
  tm_shape(houses_sf[houses_sf$town=="SENGKANG", ]) +
    tm_dots(col='min_dist_clinic',
            style='quantile',
            size=0.1)
```