---
title: "AHP File"
output: html_document
---
```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
packages = c('ahp', 'sf', 'readr', 'ahpsurvey', 'dplyr', 'tmap', 'rgdal', 'tidyverse')
for (p in packages){ 
  if(!require(p, character.only = T)){
    install.packages(p)
  }
  library(p,character.only = T) 
}
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
houses <- read_csv('data/resale-flat-prices/finalCSVforplots.csv')
```

```{r}
#Try ahp.mat
features <- c('busStop', 'clinics','hawkers','mrt','schools','spf')
weight_b_c <- 9  #Weight busstop_clinic. Bus stop is much higher priority than clinic
weight_b_h <- 7
weight_b_m <- 5
weight_b_sc <- 3
weight_b_sp <- 1
weight_c_h <- -3
weight_c_m <- -4
weight_c_sc <- -7
weight_c_sp <- -9
weight_h_m <- -3
weight_h_sc <- -5
weight_h_sp <- -6
weight_m_sc <- -7
weight_m_sp <- -9
weight_sc_sp <- -3

df <- data.frame(c(weight_b_c, weight_b_h, weight_b_m, weight_b_sc, weight_b_sp,
                   weight_c_h, weight_c_m, weight_c_sc, weight_c_sp, 
                   weight_h_m, weight_h_sc, weight_h_sp,
                   weight_m_sc, weight_m_sp,
                   weight_sc_sp))
transpose <- as.data.frame(t(df))
colnames(transpose) <- c("b_c", "b_h", "b_m", "b_sc", "b_sp",
                         "c_h", "c_m", "c_sc", "c_sc",
                         "h_m", "h_sc", "h_sp",
                         "m_sc", "m_sp",
                         "sc_sp")
rownames(transpose) <- "row"

ahp_mat <- transpose %>% ahp.mat(df = transpose, atts = features, negconvert = T) %>% head(3)
priorities <- ahp.indpref(ahp_mat, features)

priorities$busStop
```

```{r}
houses$ahp<- 
  houses$min_dist_busStop*priorities$busStop + houses$min_dist_clinic*priorities$clinics +
  houses$min_dist_hawker*priorities$hawkers  + houses$min_dist_mrt*priorities$mrt +
  houses$min_dist_school*priorities$schools  + houses$min_dist_spf*priorities$spf
```

```{r}
tmap_mode('plot')
tm_shape(mpsz) + tm_polygons() + 
  tm_shape(houses_sf) +
    tm_dots(col='ahp', #School here but change to anything
            style='quantile',
            size=0.5)

```
```{r}
# features <- c('busStop', 'clinics','hawkers','mrt','schools','spf')
# weight_b_c <- 9  #Weight busstop_clinic. Bus stop is much higher priority than clinic
# weight_b_h <- 7
# weight_b_m <- 5
# weight_b_sc <- 3
# weight_b_sp <- 1
# weight_c_h <- 1/3
# weight_c_m <- 1/4
# weight_c_sc <- 1/7
# weight_c_sp <- 1/9
# weight_h_m <- 1/3
# weight_h_sc <- 1/5
# weight_h_sp <- 1/6
# weight_m_sc <- 1/7
# weight_m_sp <- 1/9
# weight_sc_sp <- 1/3
# 
# #Create preference matrix
# prefMatrix <- data.frame(c(1,weight_b_c,weight_b_h,weight_b_m,weight_b_sc,weight_b_sp),
#                         c(weight_b_c,1,weight_c_h,weight_c_m,weight_c_sc,weight_c_sp),
#                         c(weight_b_h,weight_c_h,1,weight_h_m,weight_h_sc,weight_h_sp),
#                         c(weight_b_m,weight_c_m,weight_h_m,1,weight_m_sc,weight_m_sp),
#                         c(weight_b_sc,weight_c_sc,weight_h_sc,weight_m_sc,1,weight_sc_sp),
#                         c(weight_b_sp,weight_c_sp,weight_h_sp,weight_m_sp,weight_sc_sp,1))
# 
# colnames(prefMatrix) <- c(1:6)
# 
# prefComb <- data.frame(c(1,2,1/9),c(2,3,3),c(1,2,5))
# #Create AHP Matrix
# ahpMat <- AhpMatrix(prefMatrix)
# ahpMat2 <- AhpMatrix(prefComb)
# 
# #Calculate the ahp priority weights from the AHP matrix.
# priorities <- PrioritiesFromPairwiseMatrixEigenvalues(ahpMat)
# priorities2 <- PrioritiesFromPairwiseMatrixEigenvalues(ahpMat2)
# 
# 
# priorities$priority
# priorityList <- priorities$priority
# priorityList2 <- priorities2$priority
# consistency <- priorities$consistency
# 
# print(priorityList)
# print("Consistency: ")
# print(consistency)
```