```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
packages = c('sf', 'ClustGeo','spdep', 'tmap', 'tidyverse', 'ggmap')
for (p in packages){ 
  if(!require(p, character.only = T)){
    install.packages(p) 
  }
  library(p,character.only = T) 
}
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
register_google(key="AIzaSyCauc5SBxNAfU1NO2k9H5eVeBlrZKeQ63k")
``` 

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
flat_90_99 <- read_csv("data/resale-flat-prices/resale-flat-prices-based-on-approval-date-1990-1999.csv")
flat_00_12 <- read_csv("data/resale-flat-prices/resale-flat-prices-based-on-approval-date-2000-feb-2012.csv")
flat_12_14 <- read_csv("data/resale-flat-prices/resale-flat-prices-based-on-registration-date-from-mar-2012-to-dec-2014.csv")
flat_15_onwards <- read_csv("data/resale-flat-prices/resale-flat-prices-based-on-registration-date-from-jan-2015-onwards.csv")
#head(flat_90_99)
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
#To make all columns same
flat_15_onwards <- flat_15_onwards %>% select(-remaining_lease)
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
#all_flats <- rbind.data.frame(flat_90_99, flat_00_12, flat_12_14, flat_15_onwards)
#all_flats$address <- paste(all_flats$street_name, " block ", all_flats$block)
#all_flats_distinct <- distinct(all_flats, address)
#all_flats_1_to_100 <- all_flats_distinct[1:100, ]
#all_flats_101_to_200 <- all_flats_distinct[101:200, ]
#all_flats_201_to_700 <- all_flats_distinct[201:700, ]

#all_flats_temp <- all_flats_distinct[4001:8904, ]
#all_flats_location_temp <- mutate_geocode(all_flats_temp, address)
```

```{r}
#all_flats_details_1_to_8904 <- inner_join(all_flats , all_flats_location_1_to_8904)
#write.csv(all_flats_details_1_to_8904, file = "data/resale-flat-prices/resale_flat_prices_1_to_8904_geolocated.csv")
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
rental_flats <- read_csv("data/rental-flats/rental_flats.csv")
rental_flats$address = paste(rental_flats$Street_Name, " block ", rental_flats$Block_No)
rental_flats_distinct = distinct(rental_flats, address)
```

```{r}
#rental_flat_location <- mutate_geocode(rental_flats_distinct, address)
#head(rental_flat_location)
```

```{r}
#rental_flat_90_99_location <- inner_join(rental_flats, rental_flat_location)
```

```{r}
#write.csv(rental_flat_90_99_location, file = "data/resale-flat-prices/resale_flat_prices_90_99_geolocated.csv")
```

```{r}
houses_getlocated <- read_csv('data/resale-flat-prices/resale_flat_prices_1_to_8904_geolocated.csv')
```

```{r}
#houses_distinct <- distinct(houses, address)
#houses_distinct <- inner_join(houses, houses_distinct)
#houses_group <- houses %>% group_by(address) %>% summarise(town = sample(town, 1), flat_type = sample(flat_type, 1), lon=sample(lon, 1), lat = sample(lat, 1))

houses_group <- na.omit(houses_group)
#write.csv(houses_group, file = "data/resale-flat-prices/all_flats.csv")

houses_by_street <- houses_getlocated %>% group_by(street_name) %>% summarise(town = sample(town, 1), flat_type = sample(flat_type, 1), lon=sample(lon, 1), lat = sample(lat, 1))
```

```{r}
houses <- read_csv('data/resale-flat-prices/all_flats_with_group.csv')
houses_grouped <- read_csv('data/resale-flat-prices/all_flats_grouped.csv')
```

# Data Cleaning

Some coordinates have been incorrectly calculated. We will be replacing them
For example, coordinates for Nile road is (-36.6, 174.7) which is actually the coordinates for Nile road in New Zealand. Thus, we will be replacing those with the actual coordinates
```{r}
#Fix coordinates for Nile Road
houses[4977,]$lat = 1.288820
houses[4977,]$lon = 103.83004
houses[4978,]$lat = 1.288820
houses[4978,]$lon = 103.83004

#Fix coordinates for Alexandra Road
houses[51,]$lat = 1.287240
houses[51,]$lon = 103.802550

#Fix coordinates for Geylang
houses[3669,]$lat = 1.31453
houses[3669,]$lon = 103.88246
houses <- houses[c(1,4:11)]

write_csv(houses, 'data/resale-flat-prices/all_flats_with_group.csv')
```

```{r}
#Change for Nile Road
houses_grouped[322,]$lat = 1.288820
houses_grouped[322,]$lon = 103.83004

#Fix coordinates for Geylang
houses_grouped[231,]$lat = 1.31453
houses_grouped[231,]$lon = 103.88246

#Fix coordinates for Alexandra Road
houses_grouped[4,]$lat = 1.287240
houses_grouped[4,]$lon = 103.802550
write_csv(houses_grouped, 'data/resale-flat-prices/all_flats_grouped.csv')

```

#Get all that are not in Singapore

```{r}
houses <- read_csv('data/resale-flat-prices/all_flats_with_group.csv')
incorrect_coord <- houses[(houses$lon<103.59 | houses$lon>104.07 | houses$lat<1.13 | houses$lat>1.47),]

incorrect_coord$address <- paste(incorrect_coord$address, " Singapore")
incorrect_coords_loc <- mutate_geocode(incorrect_coord, address)

#Queenstown is still incorrect
incorrect_coords_loc[incorrect_coords_loc$town=="QUEENSTOWN",]$lon1 = 103.799
incorrect_coords_loc[incorrect_coords_loc$town=="QUEENSTOWN",]$lat1 = 1.3033

write_csv(incorrect_coords_loc, 'data/resale-flat-prices/incorrect_coords.loc')

x1_incorrect <- incorrect_coords_loc$X1

houses$lon <- ifelse(houses$X1 %in% x1_incorrect, incorrect_coords_loc$lon1, houses$lon)
houses$lat <- ifelse(houses$X1 %in% x1_incorrect, incorrect_coords_loc$lat1, houses$lat)


#Now that incorrect coordinates have been rectified, we will be merging back to houses
houses_without_group <- houses[,c(1:7)]
houses_with_group <- houses[,c(1:8)]

write_csv(houses_without_group, 'data/resale-flat-prices/all_flats.csv')
write_csv(houses_with_group, 'data/resale-flat-prices/all_flats_with_group.csv')

houses_sep <- houses_with_group %>% separate(address, c("Street", "Block"), sep="block")
houses_group <- houses_sep %>% group_by(Street) %>% summarise(lon = mean(lon), lat=mean(lat))
houses_group$group_id <- c(1:length(unique(houses_group$Street)))

write_csv(houses_group, 'data/resale-flat-prices/all_flats_grouped.csv')
``` 


# GEOCODE CLINICS 

```{r}
clinics <- read_csv('data/clinics/healthcare_facilities.csv')
clinics$address <- paste(clinics$address, "Singapore")
clinics_location <- mutate_geocode(clinics, address)

write_csv(clinics_location, 'data/clinics/healthcare_facilities.csv')
```

# GEOCODE GP CLINICS

```{r}
gpclinics <- readOGR(dsn='data/clinics', layer='GPClinics')@data
gpclinics$address <- paste(gpclinics$EST_ADD_BL, gpclinics$EST_ADD_ST, "Singapore")
gpclinics_location <- mutate_geocode(gpclinics, address)

gpclinics_location[451307,]$lat <- 1.317270
gpclinics_location[451307,]$lon <- 103.897510

gpclinics_location_uniq[176,]$lat <- 1.317270
gpclinics_location_uniq[176,]$lon <- 103.897510

gpclinics_location_uniq <- gpclinics_location %>% distinct(address, .keep_all = TRUE)
write_csv(gpclinics_location_uniq, 'data/clinics/gpclinics.csv')
```

# GEOCODE SCHOOLS

```{r}
schools <- read_csv('data/schools/general-information-of-schools.csv')
schools <- schools %>% select(c(school_name, address, postal_code, dgp_code, zone_code))

schools$address <- paste(schools$address, "Singapore")
schools_location <- mutate_geocode(schools, address)

write_csv(schools_location, 'data/schools/schools.csv')
```