---
title: "Project - Phase 2"
output: html_notebook
---

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
packages = c('sf', 'tmap', 'ggmap', 'rgdal', 'tidyverse', 'qdapTools')
for (p in packages){ 
  if(!require(p, character.only = T)){
    install.packages(p) 
  }
  library(p,character.only = T) 
}
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
houses <- read_csv('data/resale-flat-prices/all_flats.csv')
mpsz <- readOGR(dsn='data/mpsz', layer='MP14_SUBZONE_WEB_PL')
houses_sf <- st_as_sf(houses, coords = c("lon", "lat"))
req_crs <- CRS("+init=epsg:4326")
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
#Add group ID to each house
houses_sep <- houses %>% separate(address, c("Street", "Block"), sep="block")
houses_group <- houses_sep %>% group_by(Street) %>% summarise(lon = mean(lon), lat=mean(lat))
houses_group$group_id <- c(1:length(unique(houses_group$Street)))

houses$Street <- houses_sep$Street
houses_group_ids <- houses_group[, c("group_id", "Street")]

houses <- inner_join(houses, houses_group_ids)

houses_group_test <- houses_group[1:5, ]
```

## BUS STOP 

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
busStop <- readOGR(dsn='data/BusStop', layer='BusStop')
busStop <- spTransform(busStop, req_crs)

busStop.data <- busStop@data
busStop.coords <- busStop@coords

busStop.data$lon <- busStop@coords[,1]
busStop.data$lat <- busStop@coords[,2]

buses_test <- busStop.data[1:5,]
```

### Calculate closest distance of each group from the bus stops

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
houses_latlon <- houses_group_test[, c("lat", "lon")]
buses_latlon <- buses_test[, c("lat", "lon")]

dist(rbind(houses_latlon, buses_latlon), method="euclidean")
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
plot(houses_latlon)
plot(buses_latlon)
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
crossdist(houses_latlon, buses_latlon)
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```


```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```


```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```


```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```