---
title: "Project - Initial Plots"
---

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
packages = c('sf', 'tmap', 'ggmap', 'rgdal', 'tidyverse')
for (p in packages){ 
  if(!require(p, character.only = T)){
    install.packages(p) 
  }
  library(p,character.only = T) 
}
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
houses <- read_csv('data/resale-flat-prices/all_flats.csv')
mpsz <- readOGR(dsn='data/mpsz', layer='MP14_SUBZONE_WEB_PL')
houses_sf <- st_as_sf(houses, coords = c("lon", "lat"))
```

## BUS STOP 

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
busStop <- readOGR(dsn='data/BusStop', layer='BusStop')

busStop.data <- busStop@data
busStop.data <- distinct(busStop@data, 'BUS_sTOP_N')
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
tm_shape(mpsz) + tm_polygons() +
  tm_shape(busStop) + tm_dots()
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
#BUS STOP AND HOUSES
tmap_mode('plot')
tm_shape(mpsz) + tm_polygons() + 
  tm_shape(houses_sf) + tm_bubbles(col='flat_type') +
  tm_shape(busStop) + tm_dots()

```

## TAXI STOP

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
taxiStop <- readOGR(dsn='data/taxistand', layer='TaxiStop')
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
tm_shape(mpsz) + tm_polygons() +
  tm_shape(taxiStop) + tm_dots()
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
#For all KML files
ogrListLayers("data/clinics/MOH_CHAS_CLINICS.kml")
clinics <- readOGR(dsn="data/clinics/MOH_CHAS_CLINICS.kml", layer="MOH_CHAS_CLINICS")
```
```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
tm_shape(mpsz) + tm_polygons() +
  tm_shape(clinics) + tm_dots()
```

## HAWKER CENTRES 

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
ogrListLayers("data/hawker-centres/hawker-centres-kml.kml")
hawker_centres <- readOGR(dsn="data/hawker-centres/hawker-centres-kml.kml", layer="HAWKERCENTRE")
```



```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
tm_shape(mpsz) + tm_polygons() +
  tm_shape(hawker_centres) + tm_dots()
```

## MRT STATION

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
ogrListLayers("data/mrtstation/lta-mrt-station-exit-kml.kml")
mrt_station <- readOGR(dsn="data/mrtstation/lta-mrt-station-exit-kml.kml", layer="MRT_EXITS")
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
tm_shape(mpsz) + tm_polygons() +
  tm_shape(mrt_station) + tm_dots()
```

## Pre-SCHOOLS

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
ogrListLayers("data/schools/pre-schools-location-kml.kml")
pre_schools <- readOGR(dsn="data/schools/pre-schools-location-kml.kml", layer="PRESCHOOLS_LOCATION")
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
tm_shape(mpsz) + tm_polygons() +
  tm_shape(pre_schools) + tm_dots()
```

## SINGAPORE POLICE FORCE ESTABLISHMENT 

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
ogrListLayers("data/singapore-police-force-establishment/singapore-police-force-establishments-2018-kml.kml")
singapore_police <- readOGR(dsn="data/singapore-police-force-establishment/singapore-police-force-establishments-2018-kml.kml", layer="SPF_ESTABLISHMENTS_2018")
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
tm_shape(mpsz) + tm_polygons() +
  tm_shape(singapore_police) + tm_dots()
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```
