---
title: "Project - MRT - Print"
output: html_notebook
---

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
packages = c('ggmap', 'rgdal','qdapTools', 'spatstat', 'readr', 'dplyr', 'sf', 'tmap','tmaptools')
for (p in packages){ 
  if(!require(p, character.only = T)){
    install.packages(p) 
  }
  library(p,character.only = T) 
}
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
housesfinalv1<- read_csv('data/resale-flat-prices/finalCSVforplots.csv')
houses_grouped_sf <- st_as_sf(housesfinalv1, coords = c("lon", "lat"))
houses_sf <- st_set_crs(houses_sf, 4326)
houses_sf <- st_transform(houses_sf, 3414)

mpsz <- readOGR(dsn='data/mpsz', layer='MP14_SUBZONE_WEB_PL')
mpsz_sf <- st_as_sf(mpsz)
```


```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
summary(housesfinalv1)
```


#HISTOGRAM of REGIONS

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
houses_agg <- houses_sf %>% group_by(REGION_N) %>% summarise(mean_dist=mean(min_dist_clinic))

ggplot(houses_agg, aes(x = reorder(REGION_N, -mean_dist),y = mean_dist)) + 
  geom_col() + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```


#HISTOGRAM of 1 region by subzone

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
houses_agg <- houses_sf[houses_sf$REGION_N=="CENTRAL REGION", ] %>% group_by(SUBZONE_N) %>% summarise(mean_dist=mean(min_dist_clinic))

ggplot(houses_agg, aes(x = reorder(SUBZONE_N, -mean_dist),y = mean_dist)) + 
  geom_col() + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

#HISTOGRAM of 1 region by town

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
houses_agg <- houses_sf[houses_sf$REGION_N=="CENTRAL REGION", ] %>% group_by(town) %>% summarise(mean_dist=mean(min_dist_clinic))

ggplot(houses_agg, aes(x = reorder(town, -mean_dist),y = mean_dist)) + 
  geom_col() + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```


#Create the plot on a region level 

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
houses_agg <- houses_grouped_sf %>% group_by(REGION_N) %>% summarise(mean_dist=mean(min_dist_mrt))

mrthist <- ggplot(houses_agg, aes(x = REGION_N, mean_dist)) + 
  geom_col(fill = '#336e7b') + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) + theme(axis.title = element_text(family = "Trebuchet MS", color="#666666", face="bold", size=15)) 

mrthist
```


#Set Plot Panel Background

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
# Change the colors of plot panel background to lightblue and the color of grid lines to white
mrthist + theme(
  panel.background = element_rect(fill = "#e4e9ed",
                                colour = "#e4e9ed",
                                size = 0.5, linetype = "solid"),
  panel.grid.major = element_line(size = 0.5, linetype = 'solid',
                                colour = "white"), 
  panel.grid.minor = element_line(size = 0.25, linetype = 'solid',
                                colour = "white")
  )
```

#Create the plot by town

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
houses_agg <- houses_grouped_sf %>% group_by(town) %>% summarise(mean_dist=mean(min_dist_mrt))

mrthist <- ggplot(houses_agg, aes(x = town, mean_dist)) + 
  geom_col(fill = '#336e7b') + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) + theme(axis.title = element_text(family = "Trebuchet MS", color="#666666", face="bold", size=15)) 

mrthist
```


#Set Plot Panel Background

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
# Change the colors of plot panel background to lightblue and the color of grid lines to white
mrthist + theme(
  panel.background = element_rect(fill = "#e4e9ed",
                                colour = "#e4e9ed",
                                size = 0.5, linetype = "solid"),
  panel.grid.major = element_line(size = 0.5, linetype = 'solid',
                                colour = "white"), 
  panel.grid.minor = element_line(size = 0.25, linetype = 'solid',
                                colour = "white")
  )
```


#Create the plot by subzone

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
houses_agg <- houses_grouped_sf %>% group_by(SUBZONE_N) %>% summarise(mean_dist=mean(min_dist_mrt))

mrthist <- ggplot(houses_agg, aes(x = SUBZONE_N, mean_dist)) + 
  geom_col(fill = '#336e7b') + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) + theme(axis.title = element_text(family = "Trebuchet MS", color="#666666", face="bold", size=15)) +
  coord_flip()

mrthist
```


#Set Plot Panel Background

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
# Change the colors of plot panel background to lightblue and the color of grid lines to white
mrthist + theme(
  panel.background = element_rect(fill = "#e4e9ed",
                                colour = "#e4e9ed",
                                size = 0.5, linetype = "solid"),
  panel.grid.major = element_line(size = 0.5, linetype = 'solid',
                                colour = "white"), 
  panel.grid.minor = element_line(size = 0.25, linetype = 'solid',
                                colour = "white")
  )
```


