---
title: "Project - ALL FACILITIES  - Print"
output: html_notebook
---

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
packages = c('sf', 'tmap', 'ggmap', 'rgdal', 'tidyverse', 'readr','extrafont')
for (p in packages){ 
  if(!require(p, character.only = T)){
    install.packages(p) 
  }
  library(p,character.only = T) 
}
```



```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
houses <- read_csv('data/resale-flat-prices/finalCSVforplots.csv')
houses_sf<- st_as_sf(houses, coords = c("lon", "lat"))

min_school <- houses_sf %>% group_by(SUBZONE_N) %>% summarise(mean_dist=mean(min_dist_school),
                                                              max_dist = max(min_dist_school),
                                                              min_dist = min(min_dist_school))

houses_box <- houses_sf[c(1:5),]
mpsz <- readOGR(dsn='data/mpsz', layer='MP14_SUBZONE_WEB_PL')

schools <- read_csv('data/schools/schools.csv' )
schools_sf <- st_as_sf(schools, coords=c('lon','lat' ))
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
tmap_mode('view')
tm_shape(mpsz) + tm_polygons() + 
  tm_shape(houses_sf) +
    tm_dots(col='min_dist_school', #School here but change to anything
            style='quantile',
            size=0.1) +
  tm_shape(schools_sf) +
    tm_bubbles(size=0.05)

```

#Create the plot on a subzone level

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
houses_agg <- houses_sf %>% group_by(SUBZONE_N) %>% summarise(mean_dist=mean(min_dist_school))

schoolhist <- ggplot(houses_agg, aes(x = reorder(SUBZONE_N, -mean_dist), mean_dist)) + 
  geom_col(fill = '#e05915') + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) + theme(axis.title = element_text(family = "Trebuchet MS", color="#666666", face="bold", size=15)) 

schoolhist

```


#Set Plot Panel Background

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
# Change the colors of plot panel background to lightblue and the color of grid lines to white
schoolhist + theme(
  panel.background = element_rect(fill = "#edd9c0",
                                colour = "#edd9c0",
                                size = 0.5, linetype = "solid"),
  panel.grid.major = element_line(size = 0.5, linetype = 'solid',
                                colour = "white"), 
  panel.grid.minor = element_line(size = 0.25, linetype = 'solid',
                                colour = "white")
  )
```


