---
title: "Project - MRT - Calc"
---

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
packages = c('sf', 'tmap', 'ggmap', 'rgdal', 'tidyverse', 'qdapTools', 'spatstat', 'readr')
for (p in packages){ 
  if(!require(p, character.only = T)){
    install.packages(p) 
  }
  library(p,character.only = T) 
}
```


```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
houses <- read_csv('data/resale-flat-prices/all_flats_updated.csv')
houses_grouped <- read_csv('data/resale-flat-prices/all_flats_grouped.csv')
houses_grouped_sf <- st_as_sf(houses_grouped, coords = c("lon", "lat"))

houses_grouped_df <- as.data.frame(st_coordinates(houses_grouped_sf))
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
ogrListLayers('data/mrtstation/lta-mrt-station-exit-kml.kml')
mrt <- readOGR(dsn='data/mrtstation/lta-mrt-station-exit-kml.kml',
               layer='MRT_EXITS')
mrt_sf <- st_as_sf(mrt)
mrt_df <- as.data.frame(st_coordinates(mrt_sf))
mrt_df <- mrt_df[,c(1:2)]
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
dist_matrix <- as.data.frame(crossdist(houses_grouped_df$X, houses_grouped_df$Y, mrt_df$X, mrt_df$Y))

head(dist_matrix)
#get min of all columns
dist_matrix$min_dist <- apply(dist_matrix,1,min)
dist_matrix$group <- houses_grouped$group_id

min(dist_matrix$min_dist)
max(dist_matrix$min_dist)
```


```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```


```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```


```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```


```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```


```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```


```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```


