---
title: "Project - Phase 2"
output: html_notebook
---

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
packages = c('tmap', 'ggmap', 'rgdal', 'tidyverse', 'qdapTools', 'spatstat', 'readr', 'sf')
for (p in packages){ 
  if(!require(p, character.only = T)){
    install.packages(p) 
  }
  library(p,character.only = T) 
}
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
mpsz <- readOGR(dsn='data/mpsz', layer='MP14_SUBZONE_WEB_PL')
mpsz_sf <- st_as_sf(mpsz)
mpsz_sf <- st_transform(mpsz_sf, 4326)
mpsz_sf <- mpsz_sf %>% select(SUBZONE_NO, SUBZONE_N, REGION_N, geometry)


houses <- read_csv('data/resale-flat-prices/all_flats.csv')
houses_sf <- st_as_sf(houses, coords = c("lon", "lat"))
st_crs(houses_sf) <- st_crs(mpsz_sf)

houses_group_hawk <- read_sf('data/resale-flat-prices/all_flats_grouped_hawker.csv')

str(houses_group_hawk)
houses_group_hawk_sf <- st_as_sf(houses_group_hawk)
st_crs(houses_group_hawk_sf) <- st_crs(mpsz_sf)
```

## BUS STOP 

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
busStop_sf<- st_read(dsn='data/BusStop', layer='BusStop')
busStop_sf <- st_set_crs(busStop_sf, 3414)
busStop_sf <- st_transform(busStop_sf, 4326)
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
joined_df <- st_join(mpsz_sf, houses_sf, join=st_intersects)
houses <- na.omit(joined_df)
write_csv(houses, 'data/resale-flat-prices/all_flats_with_subzone.csv')

houses_hawker <- read_csv('data/resale-flat-prices/all_flats_with_group_hawker.csv')
houses$min_hawker <- houses_hawker$min_hawker
write_csv(houses, 'data/resale-flat-prices/all_flats_with_group_hawker.csv')


join_group <- st_join(mpsz_sf, houses_group_hawk_sf, join=st_intersects)
houses_group_hawk <- na.omit(join_group)

write_csv(houses_group_hawk, 'data/resale-flat-prices/all_flats_grouped_hawker.csv')
``` 






```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
#Add group ID to each house
houses_sep <- houses %>% separate(address, c("Street", "Block"), sep="block")
houses_group <- houses_sep %>% group_by(Street) %>% summarise(lon = mean(lon), lat=mean(lat))
houses_group$group_id <- c(1:length(unique(houses_group$Street)))

houses$Street <- houses_sep$Street
houses_group_ids <- houses_group[, c("group_id", "Street")]

write_csv(houses_group, 'data/resale-flat-prices/all_grouped_flats.csv')
houses <- inner_join(houses, houses_group_ids)
write_csv(houses, 'data/resale-flat-prices/all_flats_with_group.csv')

houses_group_test <- houses_group[1:5, ]
```


### Calculate closest distance of each group from the bus stops

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
houses_latlon <- houses_group_test[, c("lat", "lon")]
buses_latlon <- buses_test[, c("lat", "lon")]

dist(rbind(houses_latlon, buses_latlon), method="euclidean")
```


```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

## TRY NNDist

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
X1 <- c(1,4,7)
Y1 <- c(1,4,7)
X2 <- c(2,6)
Y2 <- c(2,6)
nndist.default(X1)
nnwhich(X1)
nncross(X1, Y1)
nndist(houses_group$lat, houses_group$lon, buses_latlon$lat, buses_latlon$lon)
```

## TRY CROSS DIST
```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
crossdist(houses_latlon$lat, houses_latlon$lon, buses_latlon$lat, buses_latlon$lon)
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
crossdist(houses[1:20,]$lat, houses[1:20,]$lon, busStop.data[1:10,]$lat, busStop.data[1:10,]$lon)
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
busStop[1:20,]
```


#USE NABOR
```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
#install.packages('nabor')
library(nabor)

X1 <- c(1,4,7)
Y1 <- c(1,4,7)
X2 <- c(2,6)
Y2 <- c(2,6)


knn1 <- knn( c(X1,Y1), c(X2,Y2), k=1)
knn1$nn.idx
knn1$nn.dists
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```


```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```


```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```


```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```