---
title: "Project - MRT - Print"
output: html_notebook
---

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
packages = c('ggmap', 'rgdal','qdapTools', 'spatstat', 'readr', 'dplyr', 'sf', 'tmap','tmaptools')
for (p in packages){ 
  if(!require(p, character.only = T)){
    install.packages(p) 
  }
  library(p,character.only = T) 
}
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
housesfinalv1<- read_csv('data/resale-flat-prices/finalCSVforplots.csv')
houses_grouped_sf <- st_as_sf(housesfinalv1, coords = c("lon", "lat"))
houses_sf <- st_set_crs(houses_sf, 4326)
houses_sf <- st_transform(houses_sf, 3414)

mpsz <- readOGR(dsn='data/mpsz', layer='MP14_SUBZONE_WEB_PL')
mpsz_sf <- st_as_sf(mpsz)
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
summary(houses_sf)
```


#Set all Lollipop Theme
```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
#set theme
theme_dotplot <- 
    theme(axis.title = element_text(family = "Trebuchet MS", color="#666666", face="bold", size=12),
      panel.background = element_rect(fill = "#e4e9ed",
                                size = 0.25, linetype = "solid"),
      panel.grid.major = element_line(size = 0.3, linetype = 'solid',
                                colour = "white"),
      panel.grid.minor = element_line(size = 0.3, linetype = 'solid',
                                colour = "white"),
      panel.border = element_blank(),
      axis.ticks.y = element_blank()) 
```

#Lollipop Chart of REGIONS
```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
houses_agg <- houses_sf %>% group_by(REGION_N) %>% summarise(mean_dist=mean(min_dist_clinic))

chart_region <- ggplot(houses_agg,aes(x = reorder(REGION_N, -mean_dist), y=mean_dist, label=round(mean_dist,2))) +
    geom_segment( aes(x=reorder(REGION_N, -mean_dist), xend=REGION_N, y=0, yend=mean_dist), color="#535c68", size=2, alpha=0.7,face="bold") +
    geom_point( color="#336e7b", size=5, alpha=1) +
    geom_text(nudge_y = 20,family = "Trebuchet MS",color="#666666",face="bold") +
    coord_flip() +
  theme_dotplot +
  xlab("Mean for Minimum Distance") +
  ylab("Region for Housing and Development Board Units") 

chart_region 
```
#Colour One Region 
```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
houses_agg <- houses_sf %>% group_by(REGION_N) %>% summarise(mean_dist=mean(min_dist_clinic))

chart_region <- ggplot(houses_agg,aes(x = reorder(REGION_N, -mean_dist), y=mean_dist, label=round(mean_dist,2))) +
  geom_segment(aes(x=reorder(REGION_N, -mean_dist), xend=REGION_N, y=0, yend=mean_dist), color=ifelse(houses_agg$REGION_N=="EAST REGION","orange", "#535c68"), size=ifelse(houses_agg$REGION_N=="EAST REGION",3, 2), alpha=0.7,face="bold") +
    geom_point( color=ifelse(houses_agg$REGION_N=="EAST REGION","orange","#336e7b"), size=5, alpha=1) +
    geom_text(nudge_y = 20,family = "Trebuchet MS",color="#666666",face="bold") +
    coord_flip() +
  theme_dotplot +
  xlab("Mean for Minimum Distance") +
  ylab("Region for Housing and Development Board Units") 

chart_region 
``` 


#Lollipop Chart of 1 Region by Subzone --> SUBZONE IS NOT PLOTTED COZ OF THE TOO MANY COLUMNS right? 

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

houses_agg <- houses_sf[houses_sf$REGION_N=="CENTRAL REGION", ] %>% group_by(SUBZONE_N) %>% summarise(mean_dist=mean(min_dist_clinic))

chart_subzone <- ggplot(houses_agg,aes(x = reorder(SUBZONE_N, -mean_dist), y=mean_dist, label=round(mean_dist,2))) +
    geom_segment( aes(x=reorder(SUBZONE_N, -mean_dist), xend=SUBZONE_N, y=0, yend=mean_dist), color="#535c68", size=2, alpha=0.7,face="bold") +
    geom_point( color="#336e7b", size=5.5, alpha=1) +
    geom_text(nudge_x = 0.25,family = "Trebuchet MS",color="#666666",face="bold") +
    coord_flip() +
  theme_dotplot +
  xlab("Mean for Minimum Distance") +
  ylab("Subzone for Housing and Development Board Units") 

chart_subzone

```
 
    
#Lollipop Chart of 1 Region by Planning Area

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
houses_agg <- houses_sf[houses_sf$REGION_N=="CENTRAL REGION", ] %>% group_by(town) %>% summarise(mean_dist=mean(min_dist_clinic))

chart_pa <- ggplot(houses_agg,aes(x = reorder(town, -mean_dist), y=mean_dist, label=round(mean_dist,2))) +
    geom_segment( aes(x=reorder(town, -mean_dist), xend=town, y=0, yend=mean_dist), color="#535c68", size=2, alpha=0.7,face="bold") +
    geom_point( color="#336e7b", size=5, alpha=1) +
    geom_text(nudge_y = 20,family = "Trebuchet MS",color="#666666",face="bold") +
    coord_flip() +
    theme_dotplot +
  xlab("Mean for Minimum Distance") +
  ylab("Planning Area for Housing and Development Board Units") 

chart_pa


```

# Colour One Subzone
```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
houses_agg <- houses_sf %>% group_by(SUBZONE_N) %>% summarise(mean_dist=mean(min_dist_clinic))
houses_agg <- houses_agg[order(houses_agg$mean_dist),][c(1:10),]

chart_region <- ggplot(houses_agg,aes(x = reorder(SUBZONE_N, -mean_dist), y=mean_dist, label=round(mean_dist,2))) +
  geom_segment(aes(x=reorder(SUBZONE_N, -mean_dist), xend=SUBZONE_N, y=0, yend=mean_dist), color=ifelse(houses_agg$SUBZONE_N=="BUGIS","orange", "#535c68"), size=ifelse(houses_agg$SUBZONE_N=="BUGIS",3, 2), alpha=0.7,face="bold") +
    geom_point(color=ifelse(houses_agg$SUBZONE_N=="BUGIS","orange","#336e7b"), size=5, alpha=1) +
    geom_text(nudge_y =10,family = "Trebuchet MS",color="#666666",face="bold") + #reduce  nudge_y if we have less rows (reduced to 10)
    coord_flip() +
  theme_dotplot +
  xlab("Mean for Minimum Distance") +
  ylab("Planning Area for Housing and Development Board Units") 

chart_region 

``` 











