---
title: "Print Combined"
output: html_document
---

#MRT 
```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
packages = c('sf', 'tmap', 'ggmap', 'rgdal', 'tidyverse', 'readr','ggplot2')
for (p in packages){ 
  if(!require(p, character.only = T)){
    install.packages(p) 
  }
  library(p,character.only = T) 
}
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
houses_group_MRT <- read_csv('data/resale-flat-prices/all_flats_grouped.csv')
houses_grouped_sf <- st_as_sf(houses_group_MRT, coords = c("lon", "lat"))

mpsz <- readOGR(dsn='data/mpsz', layer='MP14_SUBZONE_WEB_PL')
mpsz_sf <- st_as_sf(mpsz)
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
tmap_mode('plot')
tm_shape(mpsz) + tm_polygons() + 
  tm_shape(houses_grouped_sf) +
    tm_dots(col='min_MRT',
            style='quantile',
            size=0.15) + 
  tm_style("col_blind")
```




#Create the plot on a subzone level

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
houses_agg <- houses_grouped_sf %>% group_by(SUBZONE_N) %>% summarise(mean_dist=mean(min_MRT))

mrthist <- ggplot(houses_agg, aes(x = SUBZONE_N, mean_dist)) + 
  geom_col(fill = '#336e7b') + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) + theme(axis.title = element_text(family = "Trebuchet MS", color="#666666", face="bold", size=15)) 

mrthist
```


#Set Plot Panel Background

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
# Change the colors of plot panel background to lightblue and the color of grid lines to white
mrthist + theme(
  panel.background = element_rect(fill = "#e4e9ed",
                                colour = "#e4e9ed",
                                size = 0.5, linetype = "solid"),
  panel.grid.major = element_line(size = 0.5, linetype = 'solid',
                                colour = "white"), 
  panel.grid.minor = element_line(size = 0.25, linetype = 'solid',
                                colour = "white")
  )
```

#Schools 
```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
houses_group_school <- read_csv('data/resale-flat-prices/all_flats_grouped.csv')
houses_grouped_sf <- st_as_sf(houses_group_school, coords = c("lon", "lat"))

mpsz <- readOGR(dsn='data/mpsz', layer='MP14_SUBZONE_WEB_PL')
mpsz_sf <- st_as_sf(mpsz)
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
tmap_mode('plot')
tm_shape(mpsz) + tm_polygons() + 
  tm_shape(houses_grouped_sf) +
    tm_dots(col='min_school',
            style='quantile',
            size=0.5)

```

#Create the plot on a subzone level

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
houses_agg <- houses_grouped_sf %>% group_by(SUBZONE_N) %>% summarise(mean_dist=mean(min_school))

schoolhist <- ggplot(houses_agg, aes(x = SUBZONE_N, mean_dist)) + 
  geom_col(fill = '#e05915') + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) + theme(axis.title = element_text(family = "Trebuchet MS", color="#666666", face="bold", size=15)) 

schoolhist

```


#Set Plot Panel Background

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
# Change the colors of plot panel background to lightblue and the color of grid lines to white
schoolhist + theme(
  panel.background = element_rect(fill = "#edd9c0",
                                colour = "#edd9c0",
                                size = 0.5, linetype = "solid"),
  panel.grid.major = element_line(size = 0.5, linetype = 'solid',
                                colour = "white"), 
  panel.grid.minor = element_line(size = 0.25, linetype = 'solid',
                                colour = "white")
  )
```

#Hawker Centres

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
houses_group_hawker <- read_csv('data/resale-flat-prices/all_flats_grouped.csv')
houses_grouped_sf <- st_as_sf(houses_group_hawker, coords = c("lon", "lat"))

mpsz <- readOGR(dsn='data/mpsz', layer='MP14_SUBZONE_WEB_PL')
mpsz_sf <- st_as_sf(mpsz)
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
ogrListLayers("data/hawker-centres/hawker-centres-kml.kml")
hawker_centres <- readOGR(dsn="data/hawker-centres/hawker-centres-kml.kml", layer='HAWKERCENTRE')

hc_sf <- st_as_sf(hawker_centres)
hc_sf <- st_set_crs(hc_sf, 4326)
hc_sf <- st_transform(hc_sf, 3414)

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
tmap_mode('plot')
tm_shape(mpsz) + tm_polygons() + 
  tm_shape(houses_grouped_sf) +
    tm_dots(col='min_hawker',
            style='quantile',
            size=0.5)
```

#Create the plot on a subzone level

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
houses_agg <- houses_grouped_sf %>% group_by(SUBZONE_N) %>% summarise(mean_dist=mean(min_hawker))

ggplot(houses_agg, aes(x = SUBZONE_N, mean_dist)) + 
  geom_col() + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

#Clinics

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
houses_group <- read_csv('data/resale-flat-prices/all_flats_grouped.csv')
houses_grouped_sf <- st_as_sf(houses_group, coords = c("lon", "lat"))

mpsz <- readOGR(dsn='data/mpsz', layer='MP14_SUBZONE_WEB_PL')
mpsz_sf <- st_as_sf(mpsz)
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
tmap_mode('plot')
tm_shape(mpsz) + tm_polygons() + 
  tm_shape(houses_grouped_sf) +
    tm_dots(col='min_clinic',
            style='quantile',
            size=0.5)
```

#Create the plot on a subzone level

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
houses_agg <- houses_grouped_sf %>% group_by(SUBZONE_N) %>% summarise(mean_dist=mean(min_clinic))

ggplot(houses_agg, aes(x = SUBZONE_N, mean_dist)) + 
  geom_col() + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```
