---
title: "Project - Edit Data"
output: html_notebook
---

This file contains the code for:
1. Merging the facilities and houses with boundaries
2. Changing KML files to CSVs
3. Extracting names from description in KML files


```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
packages = c('rgdal', 'tidyverse', 'qdapTools', 'spatstat', 'readr', 'sf')
for (p in packages){ 
  if(!require(p, character.only = T)){
    install.packages(p) 
  }
  library(p,character.only = T) 
}
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
mpsz <- readOGR(dsn='data/mpsz', layer='MP14_SUBZONE_WEB_PL')
mpsz_sf <- st_as_sf(mpsz)
mpsz_sf <- st_transform(mpsz_sf, 3414)
mpsz_sf <- mpsz_sf %>% dplyr::select(SUBZONE_NO, SUBZONE_N, PLN_AREA_N,REGION_N,geometry)


houses <- read_csv('data/resale-flat-prices/finalCSVforplots.csv')
houses_sf <- st_as_sf(houses, coords = c("lon", "lat"))
st_crs(houses_sf) <- st_crs(mpsz_sf)
```

# Add Subzone

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
joined_df <- st_join(mpsz_sf, houses_sf, join=st_intersects)
joined_df <- na.omit(joined_df) 
joined_df <- joined_df[,c(1:5)]
st_geometry(joined_df) <- NULL

houses <- left_join(houses, joined_df)

houses_old <- read_csv('data/resale-flat-prices/finalCSVforplots.csv')
houses_old$PLN_AREA_N <- houses$PLN_AREA_N
houses_old <- houses_old %>% dplyr::select(X1, address, town, flat_type, lon, lat, Street, SUBZONE_NO, SUBZONE_N,REGION_N, PLN_AREA_N, everything())

write_csv(houses_old, 'data/resale-flat-prices/finalCSVforplots.csv')
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
# Add subzone, plan area, region to schools

mpsz_sf <- mpsz_sf[,c(2,3,6,8)]
schools <- read_csv('data/schools/schools.csv')
schools_sf <- st_as_sf(schools, coords = c("lon", "lat"))
#schools <- schools[!grepl("JUNIOR COLLEGE", schools$school_name),]
schools_sf <- st_set_crs(schools_sf, 4326)
schools_sf <- st_transform(schools_sf, 3414)

joined_df <- st_join(schools_sf, mpsz_sf, join=st_intersects)
joined_df <- na.omit(joined_df)
st_geometry(joined_df) <- NULL

schools <- left_join(schools, joined_df)

write_csv(schools, 'data/schools/schools.csv')
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
clinics <- read_csv('data/clinics/healthcare_facilities.csv')
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
#ogrListLayers('data/clinics/GPClinics')
#gpclinics <- readOGR(dsn = 'data/clinics/GPClinics', layer = 'data/clinics/GPClinics')
gpclinics <- readOGR(dsn='data/clinics', layer='GPClinics')@data

gpclinics <- read_csv('data/clinics/gpclinics.csv')
colnames(gpclinics) <- c('name', 'address', 'postal', 'lat', 'lon')
gpclinics <- gpclinics %>% dplyr::select('EST_NAME', 'address', 'EST_ADD_PO', 'lat', 'lon')
all_clinics <- rbind.data.frame(clinics, gpclinics)
write_csv(all_clinics_na, 'data/clinics/all_clinics.csv')

gpclinics <- na.omit(gpclinics)
write_csv(gpclinics, 'data/clinics/gpclinics.csv')
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
#Add subzone etc to gplicics
#gpclinics <- readOGR(dsn='data/clinics', layer='GPClinics')@data

gpclinics <- read_csv('data/clinics/gpclinics.csv')
clinics_sf <- st_as_sf(gpclinics, coords = c("lon", "lat"))
clinics_sf <- st_set_crs(clinics_sf, 4326)
clinics_sf <- st_transform(clinics_sf, 3414)


joined_df <- st_join(clinics_sf, mpsz_sf, join=st_intersects)
joined_df <- na.omit(joined_df)
st_geometry(joined_df) <- NULL

clinics <- left_join(gpclinics, joined_df)
#write_csv(clinics, 'data/clinics/gpclinics.csv')
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
#Add subzone etc in hawker
ogrListLayers(dsn='data/hawker-centres/hawker-centres-kml.kml')
hawkers <- readOGR(dsn='data/hawker-centres/hawker-centres-kml.kml', layer='HAWKERCENTRE')
hawkers_sf <- st_as_sf(hawkers)
hawkers_sf <- st_set_crs(hawkers_sf, 4326)
hawkers_sf <- st_transform(hawkers_sf, 3414)

joined_df <- st_join(hawkers_sf, mpsz_sf, join=st_intersects)
joined_df <- na.omit(joined_df)
st_geometry(joined_df) <- NULL
coords <- st_coordinates(hawkers_sf)
joined_df$lon <- coords[,1]
joined_df$lat <- coords[,2]

st_write(hawkers_sf, dsn='data/hawker-centres/hawker-centres-kml-3.kml', layer='HAWKERCENTRE_3')
write_csv(joined_df, 'data/hawker-centres/hawker-centres.csv')
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
ogrListLayers('data/busStops/bus-stops.kml')
busStops <- readOGR(dsn='data/busStops/bus-stops.kml', layer='Layer #0')
busStops_sf <- st_as_sf(busStops)
busStops_sf <- st_transform(busStops_sf, 3414)
busStops_sf <- st_transform(busStops_sf, 4326)

busStops_sf <- busStops_sf[-c(2048,2049, 2052, 2244),]
joined_df <- st_join(busStops_sf, mpsz_sf, join=st_intersects)

joined_df <- na.omit(joined_df)
st_geometry(joined_df) <- NULL
coords <- st_coordinates(busStops_sf)
joined_df$lon <- coords[,1]
joined_df$lat <- coords[,2]

write_csv(joined_df, 'data/busStops/bus-stops.csv')
```


```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
ogrListLayers('data/mrtstation/lta-mrt-station-exit-kml.kml')
mrt <- readOGR(dsn='data/mrtstation/lta-mrt-station-exit-kml.kml',
               layer='MRT_EXITS')
mrts_sf <- st_as_sf(mrt)
mrts_sf <- st_set_crs(mrts_sf, 4326)
mrts_sf <- st_transform(mrts_sf, 3414)

joined_df <- st_join(mrts_sf, mpsz_sf, join=st_intersects)

joined_df <- na.omit(joined_df)
st_geometry(joined_df) <- NULL
coords <- st_coordinates(mrts_sf)
joined_df$lon <- coords[,1]
joined_df$lat <- coords[,2]

write_csv(joined_df, 'data/mrtstation/mrt.csv')
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
ogrListLayers(dsn='data/singapore-police-force-establishment/singapore-police-force-establishments-2018-kml.kml')
spfs <- readOGR(dsn='data/singapore-police-force-establishment/singapore-police-force-establishments-2018-kml.kml', layer='SPF_ESTABLISHMENTS_2018')
spfs_sf <- st_as_sf(spfs)
spfs_sf <- st_set_crs(spfs_sf, 4326)
spfs_sf <- st_transform(spfs_sf, 3414)

joined_df <- st_join(spfs_sf, mpsz_sf, join=st_intersects)

joined_df <- na.omit(joined_df)
st_geometry(joined_df) <- NULL
coords <- st_coordinates(spfs_sf)
joined_df$lon <- coords[,1]
joined_df$lat <- coords[,2]

write_csv(joined_df, 'data/singapore-police-force-establishment/singapore-police-force-establishments-2018.csv')
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
#Extract description in KML files
spfs <- read_csv('data/singapore-police-force-establishment/spf.csv')

extractDesc <- function(description){
  substring <- substr(description, gregexpr('<td>', description)[1][[1]][2] + 4,
                    gregexpr('</td>', description)[1][[1]][2] -1)
  return(substring)
}

list <- lapply(X = spfs$Description, FUN = extractDesc)
list <- spfs %>% sapply(X = list, FUN = toString )

spfs$desc <- list

#write_csv(spfs, 'data/singapore-police-force-establishment/spf')
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
#Extract description in KML files
hawker <- read_csv('data/hawker-centres/hawker-centres.csv')

extractDesc <- function(description){
  substring <- substr(description, gregexpr('<td>', description)[1][[1]][18] + 4,
                    gregexpr('</td>', description)[1][[1]][18] -1)
  return(substring)
}

list <- lapply(X = hawker$Description, FUN = extractDesc)
list <- hawker %>% sapply(X = list, FUN = toString )

hawker$desc <- list
hawker <- hawker %>% select(-c(Description))
hawker <- hawker %>% select(Name, desc, everything())
write_csv(hawker, 'data/hawker-centres/hawker-centres.csv')
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
mrt <- read_csv('data/mrtstation/mrt.csv')

extractDesc <- function(description){
  substring <- substr(description, gregexpr('<td>', description)[1][[1]][1] + 4,
                    gregexpr('</td>', description)[1][[1]][1] -1)
  return(substring)
}

list <- lapply(X = mrt$Description, FUN = extractDesc)
list <- mrt %>% sapply(X = list, FUN = toString )

mrt$desc <- list
mrt <- mrt %>% select(-c(Description))
mrt <- mrt %>% select(Name, desc, everything())
write_csv(mrt, 'data/mrtstation/mrt.csv')

```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
spfs <- read_csv('data/singapore-police-force-establishment/spf.csv')
spfs <- spfs %>% select(-c(Description))
spfs <- spfs %>% select(Name, desc, everything())
write_csv(spfs, 'data/singapore-police-force-establishment/spf.csv')
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

