---
title: "All Plots - filter 2 "
---
Can't use Filter 1 to avoid git conflict

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
packages = c('ggmap', 'rgdal','qdapTools', 'spatstat', 'readr', 'dplyr', 'sf', 'tmap','tmaptools')
for (p in packages){ 
  if(!require(p, character.only = T)){
    install.packages(p) 
  }
  library(p,character.only = T) 
}
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
houses <- read_csv('data/resale-flat-prices/finalCSVforplots.csv')
houses_sf <- st_as_sf(houses, coords = c("lon", "lat"))
houses_sf <- st_set_crs(houses_sf, 4326)
houses_sf <- st_transform(houses_sf, 3414)

mpsz <- readOGR(dsn='data/mpsz', layer='MP14_SUBZONE_WEB_PL')
mpsz_sf <- st_as_sf(mpsz)
```


```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
#Color 1 subzone
houses_agg <- houses_sf %>% group_by(SUBZONE_N) %>% summarise(mean_dist=mean(min_dist_clinic))
houses_agg <- houses_agg[order(houses_agg$mean_dist),][c(1:10),]

ggplot(houses_agg, aes(x = reorder(SUBZONE_N, mean_dist),
                       y = mean_dist,
                       fill=ifelse(SUBZONE_N=="BUGIS","Highlight","Normal"))) + 
  geom_col() + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1),
        legend.title = element_blank(),
        legend.position = "none") +
  labs(x = "Subzone", y = "Mean distance") +
  scale_fill_manual(values = c('orangered', 'skyblue'))
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
#Colour 1 region
houses_agg <- houses_sf %>% group_by(REGION_N) %>% summarise(mean_dist=mean(min_dist_clinic))

ggplot(houses_agg, aes(x = reorder(REGION_N, -mean_dist),
                       y = mean_dist,
                       fill=ifelse(REGION_N=="EAST REGION","green","red"))) + 
  geom_col() + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```

#Map Select Planning Area

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
tmap_mode('view')
  tm_shape(houses_sf[houses_sf$PLN_AREA_N=="SEMBAWANG", ]) +
    tm_dots(col='min_dist_clinic',
            style='quantile',
            size=0.1)
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
foo <- vector(mode="list", length=2)
names(foo) <- c("busStop", "schools")

busStop <- read_csv('data/busStops/bus-stops.csv')
schools <- read_csv('data/schools/schools.csv')

busStop_sf <- st_as_sf(busStop, coords=c("lon", "lat"))
foo[[1]] <- busStop_sf
foo[[2]] <- schools

input <- 'busStop'

str(foo)

str(foo[input][1])

yo <- foo[input][[1]]
yo <- unlist(foo[[1]])

head(yo)
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
tmap_mode("plot")
tm_shape(yo[yo$REGION_N=="NORTH REGION", ]) + tm_dots()
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
houses_all <- read_csv('data/resale-flat-prices/all_flats.csv')
houses_all$address
```

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

```